test: remove flakiness in TestDeleteSpaceBinding
the following test case is flaky, which causes the CI to fail in the
"Verify Dependencies" jobs in the `api` and `toolchain-common` projects.

```
--- FAIL: TestDeleteSpaceBinding (0.03s)
    --- FAIL: TestDeleteSpaceBinding/with_public-viewer_disabled (0.03s)
        --- FAIL: TestDeleteSpaceBinding/with_public-viewer_disabled/lara-redhat_SpaceBinding_requeues_when_redhat_space_is_missing_and_SpaceBinding_is_too_young (0.01s)
            spacebinding_cleanup_controller_test.go:165:
                	Error Trace:	/tmp/replace-verify.Y3t/host-operator/controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go:165
                	Error:      	"0s" is not greater than "0s"
                	Test:       	TestDeleteSpaceBinding/with_public-viewer_disabled/lara-redhat_SpaceBinding_requeues_when_redhat_space_is_missing_and_SpaceBinding_is_too_young
```

See [here](https://github.com/codeready-toolchain/toolchain-common/actions/runs/31172030720/job/92845733004) for example of the failure.

Workaround: increase the deletion delay to 3 seconds and compare the time left to 2 seconds instead of 1 second (to avoid rounding errors?)

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>